#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef POPIMLIB_SWIFT_H
#define POPIMLIB_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Security;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PopIMLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC8PopIMLib10CocoaMQTT5")
@interface CocoaMQTT5 : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum CocoaMQTTCONNACKReasonCode : uint8_t;
@class MqttDecodeConnAck;
@class CocoaMQTT5Message;
@class MqttDecodePubAck;
@class MqttDecodePubRec;
@class MqttDecodePublish;
@class NSDictionary;
@class NSString;
@class MqttDecodeSubAck;
@class MqttDecodeUnsubAck;
enum CocoaMQTTDISCONNECTReasonCode : uint8_t;
enum CocoaMQTTAUTHReasonCode : uint8_t;
@class MqttDecodePubComp;
enum CocoaMQTTConnState : uint8_t;
SWIFT_PROTOCOL("_TtP8PopIMLib18CocoaMQTT5Delegate_")
@protocol CocoaMQTT5Delegate
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didConnectAck:(enum CocoaMQTTCONNACKReasonCode)ack connAckData:(MqttDecodeConnAck * _Nullable)connAckData;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didPublishMessage:(CocoaMQTT5Message * _Nonnull)message id:(uint16_t)id;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didPublishAck:(uint16_t)id pubAckData:(MqttDecodePubAck * _Nullable)pubAckData;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didPublishRec:(uint16_t)id pubRecData:(MqttDecodePubRec * _Nullable)pubRecData;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didReceiveMessage:(CocoaMQTT5Message * _Nonnull)message id:(uint16_t)id publishData:(MqttDecodePublish * _Nullable)publishData;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didSubscribeTopics:(NSDictionary * _Nonnull)success failed:(NSArray<NSString *> * _Nonnull)failed subAckData:(MqttDecodeSubAck * _Nullable)subAckData;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didUnsubscribeTopics:(NSArray<NSString *> * _Nonnull)topics unsubAckData:(MqttDecodeUnsubAck * _Nullable)unsubAckData;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didReceiveDisconnectReasonCode:(enum CocoaMQTTDISCONNECTReasonCode)reasonCode;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didReceiveAuthReasonCode:(enum CocoaMQTTAUTHReasonCode)reasonCode;
- (void)mqtt5DidPing:(CocoaMQTT5 * _Nonnull)mqtt5;
- (void)mqtt5DidReceivePong:(CocoaMQTT5 * _Nonnull)mqtt5;
- (void)mqtt5DidDisconnect:(CocoaMQTT5 * _Nonnull)mqtt5 withError:(NSError * _Nullable)err;
@optional
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didReceive:(SecTrustRef _Nonnull)trust completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didPublishComplete:(uint16_t)id pubCompData:(MqttDecodePubComp * _Nullable)pubCompData;
- (void)mqtt5:(CocoaMQTT5 * _Nonnull)mqtt5 didStateChangeTo:(enum CocoaMQTTConnState)state;
@end

SWIFT_CLASS("_TtC8PopIMLib17CocoaMQTT5Message")
@interface CocoaMQTT5Message : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface CocoaMQTT5Message (SWIFT_EXTENSION(PopIMLib))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

typedef SWIFT_ENUM(uint8_t, CocoaMQTTAUTHReasonCode, open) {
  CocoaMQTTAUTHReasonCodeSuccess = 0x00,
  CocoaMQTTAUTHReasonCodeContinueAuthentication = 0x18,
};

typedef SWIFT_ENUM(uint8_t, CocoaMQTTCONNACKReasonCode, open) {
  CocoaMQTTCONNACKReasonCodeSuccess = 0x00,
  CocoaMQTTCONNACKReasonCodeUnspecifiedError = 0x80,
  CocoaMQTTCONNACKReasonCodeMalformedPacket = 0x81,
  CocoaMQTTCONNACKReasonCodeProtocolError = 0x82,
  CocoaMQTTCONNACKReasonCodeImplementationSpecificError = 0x83,
  CocoaMQTTCONNACKReasonCodeUnsupportedProtocolVersion = 0x84,
  CocoaMQTTCONNACKReasonCodeClientIdentifierNotValid = 0x85,
  CocoaMQTTCONNACKReasonCodeBadUsernameOrPassword = 0x86,
  CocoaMQTTCONNACKReasonCodeNotAuthorized = 0x87,
  CocoaMQTTCONNACKReasonCodeServerUnavailable = 0x88,
  CocoaMQTTCONNACKReasonCodeServerBusy = 0x89,
  CocoaMQTTCONNACKReasonCodeBanned = 0x8A,
  CocoaMQTTCONNACKReasonCodeBadAuthenticationMethod = 0x8C,
  CocoaMQTTCONNACKReasonCodeTopicNameInvalid = 0x90,
  CocoaMQTTCONNACKReasonCodePacketTooLarge = 0x95,
  CocoaMQTTCONNACKReasonCodeQuotaExceeded = 0x97,
  CocoaMQTTCONNACKReasonCodePayloadFormatInvalid = 0x99,
  CocoaMQTTCONNACKReasonCodeRetainNotSupported = 0x9A,
  CocoaMQTTCONNACKReasonCodeQosNotSupported = 0x9B,
  CocoaMQTTCONNACKReasonCodeUseAnotherServer = 0x9C,
  CocoaMQTTCONNACKReasonCodeServerMoved = 0x9D,
  CocoaMQTTCONNACKReasonCodeConnectionRateExceeded = 0x9F,
};

typedef SWIFT_ENUM(uint8_t, CocoaMQTTConnState, open) {
  CocoaMQTTConnStateDisconnected = 0,
  CocoaMQTTConnStateConnecting = 1,
  CocoaMQTTConnStateConnected = 2,
};

typedef SWIFT_ENUM(uint8_t, CocoaMQTTDISCONNECTReasonCode, open) {
  CocoaMQTTDISCONNECTReasonCodeNormalDisconnection = 0x00,
  CocoaMQTTDISCONNECTReasonCodeUnspecifiedError = 0x80,
  CocoaMQTTDISCONNECTReasonCodeMalformedPacket = 0x81,
  CocoaMQTTDISCONNECTReasonCodeProtocolError = 0x82,
};

typedef SWIFT_ENUM(NSInteger, CocoaMQTTLoggerLevel, open) {
  CocoaMQTTLoggerLevelOff = 0,
  CocoaMQTTLoggerLevelError = 1,
  CocoaMQTTLoggerLevelWarning = 2,
  CocoaMQTTLoggerLevelInfo = 3,
  CocoaMQTTLoggerLevelDebug = 4,
  CocoaMQTTLoggerLevelVerbose = 5,
};

typedef SWIFT_ENUM(uint8_t, CocoaMQTTQoS, open) {
  CocoaMQTTQoSQos0 = 0,
  CocoaMQTTQoSQos1 = 1,
};

typedef SWIFT_ENUM(uint8_t, CocoaMQTTSUBACKReasonCode, open) {
  CocoaMQTTSUBACKReasonCodeGrantedQoS0 = 0x00,
  CocoaMQTTSUBACKReasonCodeGrantedQoS1 = 0x01,
  CocoaMQTTSUBACKReasonCodeGrantedQoS2 = 0x02,
  CocoaMQTTSUBACKReasonCodeUnspecifiedError = 0x80,
  CocoaMQTTSUBACKReasonCodeImplementationSpecificError = 0x83,
  CocoaMQTTSUBACKReasonCodeNotAuthorized = 0x87,
  CocoaMQTTSUBACKReasonCodeTopicFilterInvalid = 0x8F,
};

@class NSStream;
SWIFT_CLASS("_TtC8PopIMLib19FoundationTransport")
@interface FoundationTransport : NSObject <NSStreamDelegate>
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8PopIMLib21MqttConnectProperties")
@interface MqttConnectProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Decoded CONNACK properties
SWIFT_CLASS("_TtC8PopIMLib17MqttDecodeConnAck")
@interface MqttDecodeConnAck : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Decoded PUBACK properties
SWIFT_CLASS("_TtC8PopIMLib16MqttDecodePubAck")
@interface MqttDecodePubAck : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Decoded PUBCOMP properties
SWIFT_CLASS("_TtC8PopIMLib17MqttDecodePubComp")
@interface MqttDecodePubComp : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Decoded PUBREC properties
SWIFT_CLASS("_TtC8PopIMLib16MqttDecodePubRec")
@interface MqttDecodePubRec : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Decoded PUBREL properties
SWIFT_CLASS("_TtC8PopIMLib16MqttDecodePubRel")
@interface MqttDecodePubRel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
/// Decoded PUBLISH properties
SWIFT_CLASS("_TtC8PopIMLib17MqttDecodePublish")
@interface MqttDecodePublish : NSObject
/// Subscription identifiers (stored as NSNumber array for Objective-C compatibility)
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable subscriptionIdentifiers;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Decoded SUBACK properties
SWIFT_CLASS("_TtC8PopIMLib16MqttDecodeSubAck")
@interface MqttDecodeSubAck : NSObject
/// Reason codes (stored as UInt8 array for Objective-C compatibility)
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull reasonCodes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Decoded UNSUBACK properties
SWIFT_CLASS("_TtC8PopIMLib18MqttDecodeUnsubAck")
@interface MqttDecodeUnsubAck : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8PopIMLib21MqttPublishProperties")
@interface MqttPublishProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8PopIMLib16MqttSubscription")
@interface MqttSubscription : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionWebSocketTask;
@class NSData;
@class NSURLSessionTask;
SWIFT_CLASS("_TtC8PopIMLib12NativeEngine") SWIFT_AVAILABILITY(tvos,introduced=13.0) SWIFT_AVAILABILITY(watchos,introduced=6.0) SWIFT_AVAILABILITY(ios,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface NativeEngine : NSObject <NSURLSessionDataDelegate, NSURLSessionWebSocketDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session webSocketTask:(NSURLSessionWebSocketTask * _Nonnull)webSocketTask didOpenWithProtocol:(NSString * _Nullable)protocol;
- (void)URLSession:(NSURLSession * _Nonnull)session webSocketTask:(NSURLSessionWebSocketTask * _Nonnull)webSocketTask didCloseWithCode:(NSURLSessionWebSocketCloseCode)closeCode reason:(NSData * _Nullable)reason;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum PopIMConnectState : NSInteger;
SWIFT_PROTOCOL("_TtP8PopIMLib20PopIMConnectProtocol_")
@protocol PopIMConnectProtocol
@optional
- (void)onConnectionStatusChangeWithStatus:(enum PopIMConnectState)status;
- (void)onConnectionErrorWithErrMsg:(NSString * _Nonnull)errMsg code:(NSInteger)code;
@end

/// 连接状态
typedef SWIFT_ENUM(NSInteger, PopIMConnectState, open) {
/// 未知
  PopIMConnectStateUnknown = -1,
/// 连接中
  PopIMConnectStateInConnect = 0,
/// 连接成功
  PopIMConnectStateSuccess = 1,
/// 断开重连
  PopIMConnectStateReconnect = 2,
/// 链接失败
  PopIMConnectStateFail = 3,
};

enum PopIMMessageSessionType : NSInteger;
@class PopIMMessageModel;
SWIFT_CLASS("_TtC8PopIMLib22PopIMConversationModel")
@interface PopIMConversationModel : NSObject
/// targetId单聊和群聊可能会重复，需要跟type、channelId聚合成唯一建
@property (nonatomic, readonly, copy) NSString * _Nonnull targetId_type_channelId;
/// 会话类型，1-单聊、2-群聊、3-系统消息、6-超级群
@property (nonatomic) enum PopIMMessageSessionType type;
/// 当前用户 id
@property (nonatomic, copy) NSString * _Nonnull userId;
/// 目标 id
@property (nonatomic, copy) NSString * _Nonnull targetId;
/// 频道ID（超级群使用）
@property (nonatomic, copy) NSString * _Nonnull channelId;
/// 序号
@property (nonatomic) NSInteger seq;
/// 是否置顶
@property (nonatomic) BOOL isTop;
/// 是不是已删除
@property (nonatomic) BOOL isDelete;
/// 会话中头像的 url
@property (nonatomic, copy) NSString * _Nonnull portraitUrl;
/// 会话中目标的名称
@property (nonatomic, copy) NSString * _Nonnull targetName;
/// 最后一条消息（完整消息对象）
@property (nonatomic, strong) PopIMMessageModel * _Nullable lastMessage;
/// 新消息数
@property (nonatomic) NSInteger newMessageNum;
/// 会话@消息数量
@property (nonatomic) NSInteger mentionedCount;
/// —相关-设置
/// 自动删除天数
@property (nonatomic) NSInteger autoDeleteDay;
/// 会话的免打扰状态：消息状态设置：0- 免打扰， 空或者1- 提醒状态
@property (nonatomic, copy) NSString * _Nonnull notificationStatus;
/// 草稿
@property (nonatomic, copy) NSString * _Nonnull draft;
/// 更新时间
@property (nonatomic) NSInteger updateTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 会话属性变更类型（仅服务端推送触发）
typedef SWIFT_ENUM(NSInteger, PopIMConversationPropertyChangeType, open) {
/// 未读数变更（clearReadSync）
  PopIMConversationPropertyChangeTypeUnreadCount = 1,
/// 置顶状态变更（SessionChangeNtf）
  PopIMConversationPropertyChangeTypeTopStatus = 2,
/// 免打扰状态变更（SessionChangeNtf）
  PopIMConversationPropertyChangeTypeNotificationStatus = 3,
};

/// —会话代理
SWIFT_PROTOCOL("_TtP8PopIMLib25PopIMConversationProtocol_")
@protocol PopIMConversationProtocol
@optional
/// 会话发生改变，消费方通过 PopIMLibSDK.shared.getConversations() 获取最新数据
- (void)conversationDidChange;
/// 推送内容点击
/// @param type 会话的类型
/// @param targetId 对方ID
/// @param pushData 发消息是传的pushData内容，原封不动返回
- (void)didClickPushConversation:(enum PopIMMessageSessionType)type targetId:(NSString * _Nonnull)targetId pushData:(NSString * _Nonnull)pushData;
/// 会话属性变更回调（仅服务端推送触发，本地操作不回调）
/// @param conversationType 会话类型
/// @param targetId 会话目标ID
/// @param channelId 频道ID
/// @param changeType 变更类型（未读数/置顶/免打扰）
/// @discussion 当收到服务端 clearReadSync 导致未读数变化、或 SessionChangeNtf 导致置顶/免打扰状态变化时触发。
/// 本地主动操作（如 clearMessagesUnreadStatus、setConversationToTop、setConversationNotificationStatus）不会触发此回调。
- (void)conversationPropertyDidChangeWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId changeType:(enum PopIMConversationPropertyChangeType)changeType;
@end

SWIFT_CLASS("_TtC8PopIMLib20PopIMConversationTag")
@interface PopIMConversationTag : NSObject <NSCopying>
/// 签唯一标识，字符型，长度不超过 10 个字
@property (nonatomic, copy) NSString * _Nonnull tagId;
/// 长度不超过 15 个字，标签名称可以重复
@property (nonatomic, copy) NSString * _Nonnull tagName;
/// 时间戳由 SDK 内部协议栈提供
@property (nonatomic) NSInteger timestamp;
/// 标签对应的会话最大数量
@property (nonatomic) NSInteger maxCount;
/// 标签对应的会话数量
@property (nonatomic) NSInteger count;
/// 标签对应的会话列表，格式：[{“conversationType”: String, “targetId”: String, “busChannel”: String}]
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, NSString *> *> * _Nullable conversations;
/// 常见标签
/// @param tagId 标签ID
/// @param tagName 标签名称
/// @param count 会话数量
+ (PopIMConversationTag * _Nonnull)createWithTagId:(NSString * _Nonnull)tagId tagName:(NSString * _Nonnull)tagName count:(NSInteger)count SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// —会话标签代理
SWIFT_PROTOCOL("_TtP8PopIMLib28PopIMConversationTagProtocol_")
@protocol PopIMConversationTagProtocol
@optional
/// 会话标签变更回调
/// @param conversationType 会话类型
/// @param targetId 会话目标ID
/// @param busChannel 业务频道（超级群使用，其他类型可为空）
/// @discussion 当用户在其它端添加、移除、编辑会话上的标签时，会触发此回调。
/// 收到通知后，建议调用 getTagsFromConversation 方法从服务端获取指定会话的最新标签数据。
- (void)onConversationTagChangedWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId busChannel:(NSString * _Nonnull)busChannel;
@end

@class PopMentionedInfo;
/// 消息内容协议，定义消息的元信息获取方法
SWIFT_PROTOCOL("_TtP8PopIMLib27PopIMMessageContentProtocol_")
@protocol PopIMMessageContentProtocol <NSObject>
/// 指定该消息是否入库
+ (BOOL)shouldSaveToDatabase SWIFT_WARN_UNUSED_RESULT;
/// 指定该消息是否计数
+ (BOOL)shouldCountUnread SWIFT_WARN_UNUSED_RESULT;
/// 指定该消息的消息类型
+ (NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
/// 选填-at的用户集合
@property (nonatomic, strong) PopMentionedInfo * _Nullable mentionedInfo;
@end

SWIFT_CLASS("_TtC8PopIMLib19PopIMMessageContent")
@interface PopIMMessageContent : NSObject <PopIMMessageContentProtocol>
/// 原始数据
@property (nonatomic, copy) NSString * _Nonnull originString;
/// 选填-at的用户集合
@property (nonatomic, strong) PopMentionedInfo * _Nullable mentionedInfo;
+ (BOOL)shouldSaveToDatabase SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)shouldCountUnread SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 自定义消息内容基类，供外部模块继承
/// 注意：使用 <code>open</code> 关键字以允许其他模块继承
/// Swift 代码可以继承此类并重写静态方法，Objective-C 代码可以重写类方法
SWIFT_CLASS("_TtC8PopIMLib25PopIMCustomMessageContent")
@interface PopIMCustomMessageContent : PopIMMessageContent
/// 必需的初始化器，用于通过类型创建实例
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 从 originString 创建自定义消息实例
/// \param originString 原始 JSON 字符串
///
- (nonnull instancetype)initWithOriginString:(NSString * _Nonnull)originString OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC8PopIMLib24PopIMImageMessageContent")
@interface PopIMImageMessageContent : PopIMMessageContent
/// 必填-缩略图URL地址,业务自己管理,可以为空
@property (nonatomic, copy) NSString * _Nonnull thumImageUrl;
/// 必填-原图图片URL地址,业务自己管理
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
/// 必填-缩略图的宽度。
@property (nonatomic) NSInteger thumWidth;
/// 必填-缩略图的宽度。
@property (nonatomic) NSInteger thumHeight;
+ (NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PopIMSearchConversationResult;
@protocol PopIMMessageProtocol;
@class PopIMMessageSend;
@class PopReceivedStatusInfo;
enum PopIMMessageSendStatus : NSInteger;
enum PopIMMessageDirection : NSInteger;
@protocol PopMessageExpansionDelegate;
@class UNUserNotificationCenter;
@class UNNotificationResponse;
SWIFT_CLASS("_TtC8PopIMLib11PopIMLibSDK")
@interface PopIMLibSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PopIMLibSDK * _Nonnull shared;)
+ (PopIMLibSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)initWithAppKey:(NSString * _Nonnull)appKey SWIFT_METHOD_FAMILY(none);
/// @param token 通过服务端 API 注册用户（获取 Token）。融云客户端 SDK 不提供获取 Token 方法。应用程序可以调用自身服务端，从融云服务端获取 Token。
/// 取得 Token 后，客户端可以按需保存 Token，供后续连接时使用。具体保存位置取决于应用程序客户端设计。如果 Token 未失效，就不必再向融云请求 Token。
/// 建议应用程序在连接之前设置连接状态监听。连接状态
- (void)connectWithToken:(NSString * _Nonnull)token userId:(NSString * _Nonnull)userId;
/// 退出服务
/// @param isReceivePush 是否允许推送，默认为 true。如果设置为 false，将调用推送设备清除接口
- (void)disConnectWithIsReceivePush:(BOOL)isReceivePush;
- (void)addConnectionStatusChangeDelegate:(id <PopIMConnectProtocol> _Nonnull)delegate;
- (void)removeConnectionStatusChangeDelegate:(id <PopIMConnectProtocol> _Nonnull)delegate;
/// 获取连接状态
/// @result  PopIMConnectState 状态枚举
- (enum PopIMConnectState)getConnectStatus SWIFT_WARN_UNUSED_RESULT;
/// 当前长连接协议标识（“ws” / “mq”），用于 UI 显示（如 “在线-ws”、“在线-mq”）
- (NSString * _Nonnull)getConnectionProtocolTag SWIFT_WARN_UNUSED_RESULT;
- (void)addConversationChangeDelegate:(id <PopIMConversationProtocol> _Nonnull)delegate;
- (void)removeConversationChangeDelegate:(id <PopIMConversationProtocol> _Nonnull)delegate;
/// 添加会话标签变更监听
/// @param delegate 会话标签代理
/// @discussion 设置会话标签变更监听器后，当用户在其它端添加、移除、编辑会话上的标签时，都会触发 onConversationTagChanged 回调。
/// 收到通知后，建议调用 getTagsFromConversation 方法从服务端获取指定会话的最新标签数据。
- (void)addConversationTagDelegate:(id <PopIMConversationTagProtocol> _Nonnull)delegate;
/// 移除会话标签变更监听
/// @param delegate 会话标签代理
- (void)removeConversationTagDelegate:(id <PopIMConversationTagProtocol> _Nonnull)delegate;
/// 获取会话列表
/// @param completion 获取的回调
- (void)getConversationListWithCompletion:(void (^ _Nonnull)(NSArray<PopIMConversationModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 分页获取会话列表
/// \param conversationTypeList 会话类型 NSNumber 数组
///
/// \param count 数量
///
/// \param startTime 起始时间
///
/// \param completion 结果回调
///
- (void)getConversationListByPageWithConversationTypeList:(NSArray<NSNumber *> * _Nonnull)conversationTypeNumbers count:(NSInteger)count startTime:(NSInteger)startTime completion:(void (^ _Nonnull)(NSArray<PopIMConversationModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 获取未读会话列表
/// \param conversationTypeList 会话类型 NSNumber 数组
///
/// \param containBlocked 是否包含免打扰会话
///
/// \param completion 结果回调
///
- (void)getUnreadConversationListWithConversationTypeList:(NSArray<NSNumber *> * _Nonnull)conversationTypeNumbers containBlocked:(BOOL)containBlocked completion:(void (^ _Nonnull)(NSArray<PopIMConversationModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 获取未读会话列表（默认包含免打扰）
- (void)getUnreadConversationListWithConversationTypeList:(NSArray<NSNumber *> * _Nonnull)conversationTypeNumbers completion:(void (^ _Nonnull)(NSArray<PopIMConversationModel *> * _Nonnull))completion;
/// 获取会话
/// @param conversationType 会话类型
/// @param targetId 会话对方的用户ID
/// @param completion 获取的结果
- (void)getConversationWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId completion:(void (^ _Nullable)(PopIMConversationModel * _Nonnull))completion;
/// 清除会话未读数
/// 更新完成之后-结果会触发delegate - conversationDidChange
/// @param conversation 会话
- (void)clearMessagesUnreadStatus:(PopIMConversationModel * _Nonnull)conversation;
/// Objective-C 适配方法 - 获取所有会话总未读消息数（默认包含免打扰）
- (void)getTotalUnreadCountWithCompletion:(void (^ _Nonnull)(NSInteger))completion;
/// Objective-C 适配方法 - 获取所有会话总未读消息数
- (void)getTotalUnreadCountWithContainBlocked:(BOOL)containBlocked completion:(void (^ _Nonnull)(NSInteger))completion;
/// 获取单个会话的未读数
/// @param conversationType 会话类型
/// @param targetId 会话对方的用户ID
/// @param completion 获取的结果
- (void)getUnreadCountWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId completion:(void (^ _Nonnull)(NSInteger))completion;
/// Objective-C 适配方法 - 按会话类型获取总未读消息数
/// \param conversationTypeList 会话类型 NSNumber 数组
///
/// \param containBlocked 是否包含被屏蔽会话
///
/// \param completion 结果回调
///
- (void)getUnreadCountWithConversationTypeList:(NSArray<NSNumber *> * _Nonnull)conversationTypeNumbers containBlocked:(BOOL)containBlocked completion:(void (^ _Nonnull)(NSInteger))completion;
/// 获取单个会话的at消息数量
/// @param conversationType 会话类型
/// @param targetId 会话对方的用户ID
/// @return 返回@消息数量，如果会话不存在返回0
- (NSInteger)getMentionedCountWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId SWIFT_WARN_UNUSED_RESULT;
/// 获取第一条未读消息（最旧的未读消息）
/// @param conversationType 会话类型
/// @param targetId 会话 id。根据不同的 conversationType，可能是用户 id、讨论组 id、群组 id
/// @param completion 获取结果回调，返回最旧的一条未读消息，若无未读消息则返回 nil
- (void)getFirstUnreadMessageWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId completion:(void (^ _Nonnull)(PopIMMessageModel * _Nullable))completion;
/// 从本地获取被at提醒的未读消息（跨所有会话类型）
/// 结果按 sendTime 升序排列（从旧到新）
/// @param completion 异步回调，返回获取到的消息实体 PopIMMessageModel 数组
- (void)getUnreadMentionedMessagesWithCompletion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// 获取会话中未读的 @ 消息
/// @param conversationType 会话类型
/// @param targetId 会话 id。根据不同的 conversationType，可能是用户 id、讨论组 id、群组 id
/// @param count 最大 @ 消息条数，有效值范围 [1, 100]
/// @param desc true 拉取最新的 count 条数据, false 拉取最旧的 count 条数据
/// @param completion 获取未读 @ 消息的回调。回调里返回的消息列表，按照时间顺序从旧到新
- (void)getUnreadMentionedMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId count:(NSInteger)count desc:(BOOL)desc completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 获取@我的未读会话列表
/// \param conversationTypeNumbers 会话类型 NSNumber 数组
///
/// \param topPriority 是否置顶优先
///
/// \param timestamp 开始时间戳（毫秒），0 表示最新
///
/// \param count 获取数量 [1, 100]
///
/// \param completion 结果回调
///
- (void)getUnreadMentionMeConversationListWithTypes:(NSArray<NSNumber *> * _Nonnull)conversationTypeNumbers topPriority:(BOOL)topPriority timestamp:(NSInteger)timestamp count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMConversationModel *> * _Nonnull))completion;
/// 删除指定会话
/// @param conversationType 会话类型
/// @param targetId 会话对方的用户ID
/// @param completion 删除的结果回调，处理完之后会话列表会自动删除列表数据并触发delegate - conversationDidChange
- (void)removeConversationWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId completion:(void (^ _Nonnull)(BOOL))completion;
/// Objective-C 适配方法 - 按会话类型删除会话
/// \param conversationTypeList 会话类型 NSNumber 数组
///
/// \param completion 删除结果回调
///
- (void)clearConversationsWithConversationTypeList:(NSArray<NSNumber *> * _Nonnull)conversationTypeNumbers completion:(void (^ _Nonnull)(BOOL))completion;
/// Objective-C 适配方法 - 搜索会话
/// \param conversationTypeList 会话类型 NSNumber 数组
///
/// \param messageType 消息类型 NSNumber 数组
///
/// \param keyword 关键字
///
/// \param completion 结果回调
///
- (void)searchConversationsWithConversationTypeList:(NSArray<NSNumber *> * _Nonnull)conversationTypeNumbers messageType:(NSArray<NSNumber *> * _Nonnull)messageType keyword:(NSString * _Nonnull)keyword completion:(void (^ _Nonnull)(NSArray<PopIMSearchConversationResult *> * _Nonnull))completion;
/// 设置会话置顶
/// @param conversationType 会话类型
/// @param targetId 会话对方的用户ID
/// @param completion 置顶的结果回调 (success, errorMessage, errorCode)，处理完之后会话列表会自动排序并触发delegate - conversationDidChange
- (void)setConversationToTopWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId isTop:(BOOL)isTop completion:(void (^ _Nonnull)(BOOL, NSString * _Nonnull, NSInteger))completion;
/// 获取会话置顶状态
/// @param conversationType 会话类型
/// @param targetId 会话对方的用户ID
/// @param completion 置顶的状态回调
- (void)getConversationTopStatusWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId completion:(void (^ _Nonnull)(BOOL))completion;
/// @param conversationType 会话类型
/// @param targetId 对方userId
/// @param content 草稿的内容
/// @param completion 保存的结果回调
/// @completion (Bool: true 保存成功，false保存失败 )
- (void)saveTextMessageDraftWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId content:(NSString * _Nonnull)content completion:(void (^ _Nonnull)(BOOL))completion;
/// @param conversationType 会话类型
/// @param targetId 对方userId
/// @param content 草稿的内容
/// @param completion 获取结果回调
/// @completion (String?: 草稿的字符串，没设置返回nil )
- (void)getTextMessageDraftWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
/// @param conversationType 会话类型
/// @param targetId 对方userId
/// @param content 草稿的内容
/// @param completion 保存的结果回调
/// @completion (Bool: true 删除成功，false 删除失败 )
- (void)clearTextMessageDraftWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId completion:(void (^ _Nonnull)(BOOL))completion;
/// @param conversationType 会话类型
/// @param targetId 对方userId
/// @param isBlocked 是否屏蔽消息提醒
/// @param successBlock 成功回调
/// @param errorBlock 失败回调，(String - 错误的提示文本 )
- (void)setConversationNotificationStatusWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId isBlocked:(BOOL)isBlocked successBlock:(void (^ _Nonnull)(NSInteger))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// @param conversationType 会话类型
/// @param targetId 对方userId
/// @param channelId 频道ID
/// @param successBlock 成功回调,  （String = “0”设置了免打扰，反之未设置）
/// @param errorBlock 失败回调，(String - 错误的提示文本 )
- (void)getConversationNotificationStatusWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId successBlock:(void (^ _Nonnull)(NSString * _Nonnull))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// 添加会话标签
/// @param tagInfo 标签信息
/// @param successBlock 成功回调
/// @param errorBlock 失败回调 ( String - 错误信息 )
- (void)addTagWithTagInfo:(PopIMConversationTag * _Nonnull)tagInfo successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// 移除会话标签
/// @param tagInfo 标签信息
/// @param successBlock 成功回调
/// @param errorBlock 失败回调 ( String - 错误信息 )
- (void)removeTagWithTagId:(NSString * _Nonnull)tagId successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// 移除会话标签
/// @param tagInfo 标签信息
/// @param successBlock 成功回调
/// @param errorBlock 失败回调 ( String - 错误信息 )
- (void)updateTagWithTagInfo:(PopIMConversationTag * _Nonnull)tagInfo successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
- (void)getTagsWithCompletion:(void (^ _Nonnull)(NSArray<PopIMConversationTag *> * _Nullable))completion;
/// 将一个或多个会话添加到指定标签
/// @param tagId 标签ID
/// @param conversationIdentifierList 添加的会话集合
/// @param successBlock 成功回调
/// @param 失败回调
- (void)addConversationsToTagWithTagId:(NSString * _Nonnull)tagId conversationIdentifierList:(NSArray<PopIMConversationModel *> * _Nonnull)conversationIdentifierList successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
- (void)removeConversationsFromTagWithTagId:(NSString * _Nonnull)tagId conversationIdentifierList:(NSArray<PopIMConversationModel *> * _Nonnull)conversationIdentifierList successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
- (void)removeTagsFromConversation:(PopIMConversationModel * _Nonnull)conversationModel tagIds:(NSArray<NSString *> * _Nonnull)tagIds successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
- (void)getTagsFromConversation:(PopIMConversationModel * _Nonnull)conversationModel completion:(void (^ _Nonnull)(NSArray<PopIMConversationTag *> * _Nullable))completion;
/// 分页获取标签的会话
/// @param tagId  标签 ID
/// @param timestamp  会话的时间戳。获取这个时间戳之前的会话列表。首次可传 0，后续可以使用返回的 RCConversation 对象的 sentTime 或 operationTime 属性值，作为下一次查询的 startTime。推荐使用 operationTime。
/// @param count  获取的数量。当实际取回的会话数量小于 count 值时，表明已取完数据。
/// @param completion  异步回调，返回会话（PopIMConversationModel）列表。
- (void)getConversationsFromTagByPageWithTagId:(NSString * _Nonnull)tagId timestamp:(NSInteger)timestamp count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMConversationModel *> * _Nullable))completion;
/// 按标签获取未读消息数
/// @param tagId  标签 ID
/// @param containBlocked 是否包含免打扰会话的未读消息数。true：包含。false：不包含。
/// @param completion  异步回调，返回未读数量
- (void)getUnreadCountByTagWithTagId:(NSString * _Nonnull)tagId containBlocked:(BOOL)containBlocked completion:(void (^ _Nonnull)(NSInteger))completion;
/// 除标签对应会话的未读消息数
/// @param tagId  标签 ID
/// @param successBlock  成功回调
/// @param errorBlock  失败回调
- (void)clearMessagesUnreadStatusByTagWithTagId:(NSString * _Nonnull)tagId successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// 清除标签会话
/// @param tagId  标签 ID
/// @param successBlock  成功回调
/// @param errorBlock  失败回调
- (void)clearConversationsByTagWithTagId:(NSString * _Nonnull)tagId successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// 添加消息代理
/// @param delegate 消息代理者
- (void)addMessageDelegate:(id <PopIMMessageProtocol> _Nonnull)delegate;
- (void)removeMessageDelegate:(id <PopIMMessageProtocol> _Nonnull)delegate;
/// 发送消息
/// @param conversationType 会话类型
/// @param targetId 会话对方的用户ID
/// @param completion 置顶的结果回调，处理完之后会话列表会自动排序并触发delegate - conversationDidChange
- (void)sendMessageWithMessage:(PopIMMessageSend * _Nonnull)message successBlock:(void (^ _Nonnull)(PopIMMessageModel * _Nonnull))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull, PopIMMessageModel * _Nullable))errorBlock;
/// 设置消息的接收状态
/// @param msgId 消息id
/// @param receivedStatusInfo 接收状态信息
/// @param completion 操作结果回调
- (void)setMessageReceivedStatusWithMsgId:(NSString * _Nonnull)msgId receivedStatusInfo:(PopReceivedStatusInfo * _Nonnull)receivedStatusInfo completion:(void (^ _Nullable)(BOOL))completion;
/// 插入消息
/// @param conversationType 会话类型
/// @param targetId 会话对象userId
/// @param sentStatus 发送状态
/// @param content 消息的内容
/// @param sentTime 发送时间
/// @param direction 消息方向
/// @param completion 插入结果
/// @completion PopIMMessageModel? 返回的消息，如果报错会返回nil
- (void)insertMessageWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId sentStatus:(enum PopIMMessageSendStatus)sentStatus content:(id <PopIMMessageContentProtocol> _Nonnull)content sentTime:(NSInteger)sentTime direction:(enum PopIMMessageDirection)direction completion:(void (^ _Nonnull)(PopIMMessageModel * _Nullable))completion;
/// 仅从本地删除指定消息（消息 messageId）
/// @param messageIds 需要删除的消息id集合
/// @param completion 删除的的回调
/// @completion Bool 操作是不是成功
- (void)deleteMessages:(NSArray<NSString *> * _Nonnull)messageIds completion:(void (^ _Nonnull)(BOOL))completion;
/// 仅从本地删除指定消息（消息 messageId）
/// @param conversationType 会话类型
/// @param targetId 会话对方userId
/// @param completion 删除的的回调
/// @completion Bool 操作是不是成功
- (void)clearMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId completion:(void (^ _Nonnull)(BOOL))completion;
/// 彻底删除消息
/// @param conversationType 会话类型
/// @param targetId 会话对方userId
/// @param channelId 频道ID（超级群使用，默认为空）
/// @param messages 消息ID列表
/// @param completion 删除的的回调
/// @completion Bool 操作是不是成功
- (void)deleteRemoteMessageWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId messages:(NSArray<NSString *> * _Nonnull)messages completion:(void (^ _Nonnull)(BOOL))completion;
/// 彻底清除会话信息
/// @param conversationType 会话类型
/// @param targetId 会话对方userId
/// @param recordTime 时间戳。默认删除小于等于recordTime的消息。如果传0，则删除所有消息
/// @param completion 删除的的回调
/// @completion Bool 操作是不是成功
- (void)clearRemoteHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId recordTime:(NSInteger)recordTime completion:(void (^ _Nonnull)(BOOL))completion;
/// 撤回消息
/// @param message 需要删除的消息
/// @param successBlock 成功的回调
/// @param errorBlock 失败的回调
- (void)recallMessage:(PopIMMessageModel * _Nonnull)message successBlock:(void (^ _Nonnull)(PopIMMessageModel * _Nonnull))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull, PopIMMessageModel * _Nonnull))errorBlock;
/// 获取单条消息
/// @param msgId 消息id
/// @param completion 获取的结果回调
/// @block PopIMMessageModel?  返回的消息，可能为空
- (void)getMessageWithMsgId:(NSString * _Nonnull)msgId completion:(void (^ _Nonnull)(PopIMMessageModel * _Nullable))completion;
/// Objective-C 适配方法 - 获取历史消息（不包含 channelId，用于私聊和群聊）
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param oldestMessageId 最老消息 ID，可选
///
/// \param count 获取数量
///
/// \param completion 结果回调
///
- (void)getHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId oldestMessageId:(NSString * _Nullable)oldestMessageId count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 获取历史消息（包含 channelId，用于超级群）
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param channelId 频道ID（超级群使用）
///
/// \param oldestMessageId 最老消息 ID，可选
///
/// \param count 获取数量
///
/// \param completion 结果回调
///
- (void)getHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nullable)channelId oldestMessageId:(NSString * _Nullable)oldestMessageId count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 只获取远程消息（不包含 channelId，用于私聊和群聊）
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param oldestMessageId 最老消息 ID，可选
///
/// \param count 获取数量
///
/// \param completion 结果回调
///
- (void)getRemoteHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId oldestMessageId:(NSString * _Nullable)oldestMessageId count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 只获取远程消息（包含 channelId，用于超级群）
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param channelId 频道ID（超级群使用）
///
/// \param oldestMessageId 最老消息 ID，可选
///
/// \param count 获取数量
///
/// \param completion 结果回调
///
- (void)getRemoteHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nullable)channelId oldestMessageId:(NSString * _Nullable)oldestMessageId count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 只获取本地消息（不包含 channelId，用于私聊和群聊）
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param oldestMessageId 最老消息 ID，可选
///
/// \param count 获取数量
///
/// \param completion 结果回调
///
- (void)getLocalHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId oldestMessageId:(NSString * _Nullable)oldestMessageId count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 只获取本地消息（包含 channelId，用于超级群）
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param channelId 频道ID（超级群使用）
///
/// \param oldestMessageId 最老消息 ID，可选
///
/// \param count 获取数量
///
/// \param completion 结果回调
///
- (void)getLocalHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nullable)channelId oldestMessageId:(NSString * _Nullable)oldestMessageId count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// Objective-C 适配方法 - 筛选历史消息
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param messageType 消息类型 NSNumber，可选
///
/// \param oldestMessageId 最老消息 ID，可选
///
/// \param isForward 查询方向
///
/// \param count 获取数量
///
/// \param completion 结果回调
///
- (void)filterHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId messageType:(NSNumber * _Nullable)messageType oldestMessageId:(NSString * _Nullable)oldestMessageId isForward:(BOOL)isForward count:(NSInteger)count completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
- (void)getHistoryMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId sentTime:(NSInteger)sentTime beforeCount:(NSInteger)beforeCount afterCount:(NSInteger)afterCount completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
/// \param conversationType 会话类型
///
/// \param targetId 会话目标 ID
///
/// \param keyword 搜索关键字
///
/// \param objectNameList 消息类型 NSNumber 数组，可选
///
/// \param startTime 开始时间 NSNumber，可选
///
/// \param endTime 结束时间 NSNumber，可选
///
/// \param offset 偏移量
///
/// \param limit 数量
///
/// \param completion 结果回调
///
- (void)searchMessagesWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId keyword:(NSString * _Nonnull)keyword objectNameList:(NSArray<NSNumber *> * _Nullable)objectNameList startTime:(NSNumber * _Nullable)startTime endTime:(NSNumber * _Nullable)endTime offset:(NSInteger)offset limit:(NSInteger)limit completion:(void (^ _Nonnull)(NSArray<PopIMMessageModel *> * _Nonnull))completion;
- (void)setMessageExpansionListener:(id <PopMessageExpansionDelegate> _Nonnull)delegate;
- (void)removeMessageExpansionListener:(id <PopMessageExpansionDelegate> _Nonnull)delegate;
/// 设置消息拓展
/// @param conversationType 会话类型
/// @param targetId 会话对方userId
/// @param channelId 频道ID
/// @param msgId 消息id
/// @param  extraKeyVal 消息拓展的内容
/// @param successBlock 成功回调，成功会走新消息更新的逻辑，这里只告知此次的操作结果
/// @param errorBlock 失败的回调
- (void)setMessageExtraWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId msgId:(NSString * _Nonnull)msgId extraKeyVal:(NSDictionary<NSString *, id> * _Nonnull)extraKeyVal successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// 删除消息拓展
/// @param conversationType 会话类型
/// @param targetId 会话对方userId
/// @param channelId 频道ID
/// @param msgId 消息id
/// @param  keyArray 删除的key集合
/// @param successBlock 成功回调，成功会走新消息更新的逻辑，这里只告知此次的操作结果
/// @param errorBlock 失败的回调
- (void)removeMessageExpansionForkeyArrayWithConversationType:(enum PopIMMessageSessionType)conversationType targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId msgId:(NSString * _Nonnull)msgId keyArray:(NSArray<NSString *> * _Nonnull)keyArray successBlock:(void (^ _Nonnull)(void))successBlock errorBlock:(void (^ _Nonnull)(NSString * _Nonnull))errorBlock;
/// 注册自定义消息类
/// @param messageClass 遵循 PopIMMessageContentProtocol 协议的类类型
/// @discussion 注册的类将用于创建新的自定义消息实例。通过类的静态方法获取 msgType、shouldSaveToDatabase、shouldCountUnread。
/// 在 Swift 中，可以直接传递类类型，如：PopIMLibSDK.shared.registerCustomMessage(messageClass: MyCustomMessage.self)
/// 在 Objective-C 中，可以传递类，如：[PopIMLibSDK.shared registerCustomMessageWithMessageClass:[MyCustomMessage class]]
- (void)registerCustomMessageWithMessageClass:(Class <PopIMMessageContentProtocol> _Nonnull)messageClass;
/// 获取自定义消息类
/// @param msgType 消息类型标识
/// @return 自定义消息类类型，如果未注册返回 nil
- (Class <PopIMMessageContentProtocol> _Nullable)getCustomMessageTemplateWithMsgType:(NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
- (void)registerForRemoteNotifications;
/// 推送设备上报
/// @param 请在 application:didRegisterForRemoteNotificationsWithDeviceToken: 回调中将该 device token 通过 setDeviceTokenData 提供给SDK。
- (void)setDeviceTokenData:(NSData * _Nonnull)deviceToken;
- (void)didFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
/// 通知点击事件
/// 如果使用了sdk-registerForRemoteNotifications配置推送则不用理会
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceive:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
/// 设置日志级别
/// 添加日志
- (void)addLogWithText:(NSString * _Nonnull)text;
/// 获取 SDK 日志文件所在目录路径。
/// 受元数据 config 中 <code>businessLogUpload</code> 控制：开启时返回目录路径，关闭或未下发时返回空字符串。
- (NSString * _Nonnull)getLogDirectoryPath SWIFT_WARN_UNUSED_RESULT;
/// 获取版本号
/// @return 返回SDK版本号
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// 获取构建版本号
/// @return 返回SDK构建版本号
- (NSString * _Nonnull)getBuildVersion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 日志级别枚举
typedef SWIFT_ENUM(NSInteger, PopIMLogLevel, open) {
  PopIMLogLevelVerbose = 0,
  PopIMLogLevelDebug = 1,
  PopIMLogLevelInfo = 2,
  PopIMLogLevelWarning = 3,
  PopIMLogLevelError = 4,
  PopIMLogLevelNone = 5,
};

typedef SWIFT_ENUM(NSInteger, PopIMMentionedType, open) {
/// at所有人
  PopIMMentionedTypeAll = 1,
/// at部份人
  PopIMMentionedTypeUser = 2,
};

/// 消息方向
typedef SWIFT_ENUM(NSInteger, PopIMMessageDirection, open) {
/// 发送
  PopIMMessageDirectionSend = 0,
/// 接收
  PopIMMessageDirectionReceive = 1,
};

enum PopIMMessageType : NSInteger;
SWIFT_CLASS("_TtC8PopIMLib17PopIMMessageModel")
@interface PopIMMessageModel : NSObject
/// targetId单聊和群聊可能会重复，需要跟type、channelId聚合成唯一建
@property (nonatomic, readonly, copy) NSString * _Nonnull targetId_type_channelId;
/// 会话类型，1-单聊、2-群聊、3-系统消息、4-超级群
@property (nonatomic) enum PopIMMessageSessionType sessionType;
/// 会话最大seq
@property (nonatomic, copy) NSString * _Nonnull sessionSeq;
/// 目标 id
@property (nonatomic, copy) NSString * _Nonnull targetId;
/// 频道ID（超级群使用）
@property (nonatomic, copy) NSString * _Nonnull channelId;
/// 消息类型
@property (nonatomic) enum PopIMMessageType msgType;
/// 客户端ID
@property (nonatomic, copy) NSString * _Nonnull clientMsgId;
/// 实际内容
@property (nonatomic, strong) id <PopIMMessageContentProtocol> _Nonnull content;
/// 是否为提醒消息 0-否;1-普通at消息 ;2-at我的消息
@property (nonatomic) NSInteger isMentioned;
/// 发送方业务方Uid
@property (nonatomic, copy) NSString * _Nonnull fromBizUid;
/// 消息ID
@property (nonatomic, copy) NSString * _Nonnull msgId;
/// 发送时间-毫秒时间
@property (nonatomic) NSInteger sendTime;
/// 过期时间
@property (nonatomic) NSInteger expireTime;
/// 会话中头像的 url
@property (nonatomic, copy) NSString * _Nonnull portraitUrl;
/// 会话中目标的名称
@property (nonatomic, copy) NSString * _Nonnull targetName;
/// 发送状态： 成功0， 发送中1， 失败2
@property (nonatomic) enum PopIMMessageSendStatus sendStatus;
/// 删除状态 0未删除，1-已删除
@property (nonatomic) NSInteger deleteStatus;
/// 是不是已读: 0-未读，1-已读
@property (nonatomic) NSInteger isRead;
/// 0-不是离线，1-离线，默认0
@property (nonatomic) NSInteger isOffLine;
/// 消息接收时间
@property (nonatomic) NSInteger receivedTime;
/// 是否为拓展信息  0-否;1-是 为1时可以参考extra的拓展信息
@property (nonatomic) NSInteger expansion;
/// 消息扩展
@property (nonatomic, copy) NSString * _Nonnull extra;
/// 消息类别： 1内容类消息-正常的单聊、群聊等用户之间发送的消息， 2-通知类消息， 3-信令类消息， 5-自定义消息
@property (nonatomic) NSInteger msgCategory;
/// 消息类型字符串（msgTypeValue），用于自定义消息
@property (nonatomic, copy) NSString * _Nonnull msgTypeValue;
/// 消息方向: 0-发送，1-接收
@property (nonatomic, readonly) enum PopIMMessageDirection direction;
+ (PopIMMessageModel * _Nonnull)createWithInfoDic:(NSDictionary<NSString *, id> * _Nonnull)dic SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// —消息代理
SWIFT_PROTOCOL("_TtP8PopIMLib20PopIMMessageProtocol_")
@protocol PopIMMessageProtocol
@optional
/// 接收到新消息
/// @param messages 新消息列表
/// @param offline 是不是离线消息
- (void)onReceived:(NSArray<PopIMMessageModel *> * _Nonnull)messages offline:(BOOL)offline;
/// 离线消息接收完成
- (void)onOfflineMessageSyncCompleted;
/// 消息撤回的回调
/// @param message 撤回的消息
- (void)messageDidRecallWithMessages:(NSArray<PopIMMessageModel *> * _Nonnull)messages;
/// 消息删除
/// @param messages 删除消息集合
- (void)didDeleteMessages:(NSArray<PopIMMessageModel *> * _Nonnull)messages;
/// 超级群新消息接收（同步过程中）
/// @param messages 新消息列表
/// @param targetId 超级群ID
/// @param channelId 频道ID
- (void)onUltraGroupReceived:(NSArray<PopIMMessageModel *> * _Nonnull)messages targetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId;
/// 超级群消息同步完成
/// @param targetId 超级群ID
/// @param channelId 频道ID
- (void)onUltraGroupSyncCompletedWithTargetId:(NSString * _Nonnull)targetId channelId:(NSString * _Nonnull)channelId;
@end

SWIFT_CLASS("_TtC8PopIMLib16PopIMMessageSend")
@interface PopIMMessageSend : NSObject
/// 非必填，扩展标识：0-非扩展，1-扩展。如果extra不为空，expansion必须为1
@property (nonatomic) NSInteger expansion;
/// 消息的扩展信息，设置的内容会原封不动保存在消息体中，可以用于传递自定义消息等
@property (nonatomic, copy) NSString * _Nonnull extra;
/// 选填-是不是需要push-默认是false-不推送
@property (nonatomic) BOOL enablePush;
/// 选填-推送的标题，不填或者填空，不会推送
@property (nonatomic, copy) NSString * _Nonnull pushTitle;
/// 选填-推送的内容，不填或者填空，不会推送
@property (nonatomic, copy) NSString * _Nonnull pushContent;
/// 选填-推送的内容
@property (nonatomic, copy) NSString * _Nonnull pushData;
/// 必填-对方ID
@property (nonatomic, copy) NSString * _Nonnull targetId;
/// 必填-会话类型
@property (nonatomic) enum PopIMMessageSessionType conversationType;
/// 非必填， 频道ID，如果是超级群channelId不传或者传””, 将使用默认频道发送
@property (nonatomic, copy) NSString * _Nonnull channelId;
/// 消息内容
@property (nonatomic, strong) id <PopIMMessageContentProtocol> _Nullable content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 发送状态
typedef SWIFT_ENUM(NSInteger, PopIMMessageSendStatus, open) {
/// 成功
  PopIMMessageSendStatusSuccess = 0,
/// 发送中
  PopIMMessageSendStatusSending = 1,
/// 失败
  PopIMMessageSendStatusFail = 2,
};

/// 会话类型
typedef SWIFT_ENUM(NSInteger, PopIMMessageSessionType, open) {
/// 私聊
  PopIMMessageSessionTypePrivatechat = 1,
/// 群聊
  PopIMMessageSessionTypeGroupchat = 2,
/// 官方通知
  PopIMMessageSessionTypeSystem = 3,
/// 超级群
  PopIMMessageSessionTypeUltraGroup = 6,
};

/// 消息类型
typedef SWIFT_ENUM(NSInteger, PopIMMessageType, open) {
/// 未知消息
  PopIMMessageTypeUnknown = -1,
/// 正常的文本
  PopIMMessageTypeText = 0,
/// 正常的图片
  PopIMMessageTypeImage = 1,
/// 消息删除通知
  PopIMMessageTypeDelntf = 2,
/// 消息撤回通知
  PopIMMessageTypeRevokeNtf = 3,
/// 消息引用
  PopIMMessageTypeReferenceMsg = 4,
/// 扩展消息
  PopIMMessageTypeMsgExNtf = 5,
/// 合并消息
  PopIMMessageTypeCombineMsg = 6,
/// 语音消息
  PopIMMessageTypeVoiceMsg = 7,
/// 视频消息
  PopIMMessageTypeVideoMsg = 8,
/// 位置消息
  PopIMMessageTypeLbsMsg = 9,
/// 会话配置变更通知
  PopIMMessageTypeSessionChangeNtf = 10,
};

SWIFT_CLASS("_TtC8PopIMLib29PopIMSearchConversationResult")
@interface PopIMSearchConversationResult : NSObject
/// 会话信息
@property (nonatomic, strong) PopIMConversationModel * _Null_unspecified conversation;
/// 会话匹配的消息条数
@property (nonatomic) NSInteger matchCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 服务错误码
typedef SWIFT_ENUM(NSInteger, PopIMServiceErrorCode, open) {
/// 其它错误
  PopIMServiceErrorCodeOther = -1000,
/// appKey本地验证不通过
  PopIMServiceErrorCodeAppkeyUnavailable = -1001,
/// token本地验证不通过
  PopIMServiceErrorCodeTokenUnavailable = -1002,
/// userId本地验证不通过
  PopIMServiceErrorCodeUserIdUnavailable = -1003,
/// 已连接，请不要重复连接
  PopIMServiceErrorCodeAlreadyconnect = -1004,
/// 内存不足
  PopIMServiceErrorCodeInsufficientMemory = -1005,
/// 非法token
  PopIMServiceErrorCodeInvalidToken = 401,
/// 服务端内部错误
  PopIMServiceErrorCodeServerError = 500,
};

SWIFT_CLASS("_TtC8PopIMLib23PopIMTextMessageContent")
@interface PopIMTextMessageContent : PopIMMessageContent
/// 必填-消息内容-必传且不能为空
@property (nonatomic, copy) NSString * _Nonnull content;
+ (NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8PopIMLib24PopIMVideoMessageContent")
@interface PopIMVideoMessageContent : PopIMMessageContent
/// 必填-封面图链接
@property (nonatomic, copy) NSString * _Nonnull thumImageUrl;
/// 必填-封面宽度
@property (nonatomic) NSInteger thumWidth;
/// 缩略图的高度。
@property (nonatomic) NSInteger thumHeight;
/// 视频链接
@property (nonatomic, copy) NSString * _Nonnull videoUrl;
/// 视频时长
@property (nonatomic) NSInteger duration;
/// 视频大小,单位b
@property (nonatomic) NSInteger size;
+ (NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8PopIMLib24PopIMVoiceMessageContent")
@interface PopIMVoiceMessageContent : PopIMMessageContent
/// 必填-语音URL地址,业务自己管理
@property (nonatomic, copy) NSString * _Nonnull remoteUrl;
/// 必填-原图图片URL地址,业务自己管理
@property (nonatomic) NSInteger duration;
+ (NSString * _Nonnull)msgType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8PopIMLib16PopMentionedInfo")
@interface PopMentionedInfo : NSObject
/// （必填）指定 MentionedInfo 的类型。PopIMMentionedType = all 表示需要提及（@）所有人。PopIMMentionedType = user 表示需要 @ 部分人，被提及的人员需要在 userIdList 中指定。
@property (nonatomic) enum PopIMMentionedType type;
/// 被提及（@）用户的 ID 集合
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull userIdList;
/// 触发离线消息推送时，通知栏显示的内容。如果是 nil，则显示默认提示内容（“有人 @ 你”）。@消息携带的 mentionedContent 优先级最高，会覆盖所有默认或自定义的 pushContent 数据。
@property (nonatomic, copy) NSString * _Nullable mentionedContent;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 消息拓展代理
SWIFT_PROTOCOL("_TtP8PopIMLib27PopMessageExpansionDelegate_")
@protocol PopMessageExpansionDelegate
@optional
/// 消息拓展添加
/// @param expansionDic  消息扩展信息中的键值对
/// @param messages 消息内容
/// @discussion expansionDic 只包含更新的键值对，不是全部的数据。如果想获取全部的键值对，请使用 message 的 extra 属性处理。
- (void)messageExpansionDidUpdateWithExpansionDic:(NSDictionary<NSString *, id> * _Nonnull)expansionDic message:(PopIMMessageModel * _Nonnull)message;
/// 消息拓展删除
/// @param keyArray  删除的key集合
/// @param message 消息内容
/// @discussion keyArray 只包含删除的key集合，不是全部的数据。如果想获取全部的键值对，请使用 message 的 extra 属性处理。
- (void)messageExpansionDidRemoveWithKeyArray:(NSArray<NSString *> * _Nonnull)keyArray message:(PopIMMessageModel * _Nonnull)message;
@end

SWIFT_CLASS("_TtC8PopIMLib21PopReceivedStatusInfo")
@interface PopReceivedStatusInfo : NSObject
/// 是否已读：0-未读，1-已读
@property (nonatomic) NSInteger isRead;
- (nonnull instancetype)initWithIsRead:(NSInteger)isRead OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8PopIMLib14YCIMSocketTest")
@interface YCIMSocketTest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
